import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
// import Navbar from "./components/navbar";
import { NavbarDemo } from "./components/navbar-main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDemo />
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        {children} <Footer />
      </body>
    </html>
  );
}
